language: php

matrix:
  include:
    - php: 7.1
      env: dependencies=highest
    - php: 7.1
      env: dependencies=lowest
    - php: 7.2
      env: dependencies=highest
    - php: 7.2
      env: dependencies=lowest

install:
  - if [ "$dependencies" = "highest" ]; then composer update --no-interaction; fi
  - if [ "$dependencies" = "lowest" ]; then composer update --prefer-lowest --no-interaction; fi

script:
  - make test

cache:
  directories:
    - $HOME/.composer/cache